### ISSUE TITLE
Missing HS for ZK

### ISSUE THREAD

**Issue by ravindranathakila** [kow3ns/kubernetes-zookeeper#8]
Please include this in the mini:

```

---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
```
